peer dep issue
boklisten/bl-reporter pull request #28
Opened 2023-09-27 08:58 UTC by AdrianAndersen

- build: fix peerDepIssue
- 0.4.13

2023-09-27 09:00 UTC, AdrianAndersen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Bl-reporter vises ikke i bl-admin (dependency issue)](https://trello.com/c/1PctEjry/820-bl-reporter-vises-ikke-i-bl-admin-dependency-issue)

2023-09-27 10:48 UTC, LarsSelbekk requested changes
This seems to work right now, but I'm not satisfied it will work for new versions - please test that using a new version of bl-common or bl-model in bl-admin does not break bl-reporter again. worry is that making these dev dependencies means we just use whatever version bl-admin requires at runtime. I want to be sure we shouldn't be using [peer dependencies](https://blog.domenic.me/peer-dependencies/) as advised in the [ng-packagr documentation](https://github.com/ng-packagr/ng-packagr/blob/main/docs/dependencies.md).

2023-10-04 08:28 UTC, AdrianAndersen commented
yup, tested now. It works

2023-10-04 08:31 UTC, LarsSelbekk approved these changes

2023-10-04 08:31 UTC, merged